name: Python Suite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install C build tools
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential
    - name: Compile C library
      run: |
        gcc -shared -fPIC src/chess_ai/transposition_tables.c -o src/chess_ai/transposition_tables.so
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Run Unit Tests
      run: |
        pytest .
    - name: Check with black
      run: |
        black . --check
    - name: Lint with flake8
      run: |
        flake8 . --count --statistics --show-source
